apiVersion: v1
kind: ConfigMap
metadata:
  name: noticeflow-config
  namespace: noticeflow
data:
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "broadcast_db"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: noticeflow-secret
  namespace: noticeflow
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgrespassword"
  POSTGRES_PASSWORD: "postgrespassword"
